#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicProduction.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MusicProduction")]
	public partial class DcDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DcDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MusicProductionConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DcDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<File> Files
		{
			get
			{
				return this.GetTable<File>();
			}
		}
		
		public System.Data.Linq.Table<Group> Groups
		{
			get
			{
				return this.GetTable<Group>();
			}
		}
		
		public System.Data.Linq.Table<Post> Posts
		{
			get
			{
				return this.GetTable<Post>();
			}
		}
		
		public System.Data.Linq.Table<SubGroup> SubGroups
		{
			get
			{
				return this.GetTable<SubGroup>();
			}
		}
		
		public System.Data.Linq.Table<Image> Images
		{
			get
			{
				return this.GetTable<Image>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<Order> Orders
		{
			get
			{
				return this.GetTable<Order>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Admin_Delete")]
		public int Admin_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Admin_Insert")]
		public int Admin_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, firstname, lastname, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Admin_Login")]
		public ISingleResult<Admin_LoginResult> Admin_Login([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(150)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password);
			return ((ISingleResult<Admin_LoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Admin_UpdatePassword")]
		public int Admin_UpdatePassword([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(150)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.File_Delete")]
		public int File_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="UniqueIdentifier")] System.Nullable<System.Guid> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.File_Insert")]
		public int File_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="UniqueIdentifier")] System.Nullable<System.Guid> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(300)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Content", DbType="VarBinary(MAX)")] System.Data.Linq.Binary content, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="NVarChar(10)")] string type)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, content, type);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Group_Delete")]
		public int Group_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Group_Insert")]
		public int Group_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(150)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Group_Update")]
		public int Group_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(150)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Human_Delete")]
		public int Human_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Human_Insert")]
		public int Human_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(100)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(100)")] string lastName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, firstName, lastName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Image_Insert")]
		public int Image_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="UniqueIdentifier")] System.Nullable<System.Guid> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Content", DbType="VarBinary(MAX)")] System.Data.Linq.Binary content, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(3000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostId", DbType="Int")] System.Nullable<int> postId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, content, description, productId, postId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_Delete")]
		public int Post_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_Insert")]
		public int Post_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(300)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Abstract", DbType="NVarChar(3000)")] string @abstract, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Body", DbType="NVarChar(MAX)")] string body, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubGroup_Id", DbType="Int")] System.Nullable<int> subGroup_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, @abstract, body, subGroup_Id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Post_Update")]
		public int Post_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="NVarChar(300)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Abstract", DbType="NVarChar(3000)")] string @abstract, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Body", DbType="NVarChar(MAX)")] string body, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubGroup_Id", DbType="Int")] System.Nullable<int> subGroup_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, title, @abstract, body, subGroup_Id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Product_Insert")]
		public int Product_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Image", DbType="VarBinary(MAX)")] System.Data.Linq.Binary image, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Abstract", DbType="NVarChar(3000)")] string @abstract, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubGroupId", DbType="Int")] System.Nullable<int> subGroupId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, image, @abstract, description, subGroupId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SubGroup_Delete")]
		public int SubGroup_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SubGroup_Insert")]
		public int SubGroup_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Group_Id", DbType="Int")] System.Nullable<int> group_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(150)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), group_Id, name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SubGroup_Update")]
		public int SubGroup_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Group_Id", DbType="Int")] System.Nullable<int> group_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(150)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, group_Id, name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Image_Delete")]
		public int Image_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="UniqueIdentifier")] System.Nullable<System.Guid> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.File_Update")]
		public int File_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="UniqueIdentifier")] System.Nullable<System.Guid> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(300)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Content", DbType="VarBinary(MAX)")] System.Data.Linq.Binary content)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, content);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Image_Edit")]
		public int Image_Edit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="UniqueIdentifier")] System.Nullable<System.Guid> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Content", DbType="VarBinary(MAX)")] System.Data.Linq.Binary content, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(3000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostId", DbType="Int")] System.Nullable<int> postId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, content, description, productId, postId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Product_Edit")]
		public int Product_Edit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Image", DbType="VarBinary(MAX)")] System.Data.Linq.Binary image, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Abstract", DbType="NVarChar(3000)")] string @abstract, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubGroupId", DbType="Int")] System.Nullable<int> subGroupId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, image, @abstract, description, subGroupId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Product_Delete")]
		public int Product_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Order_Checked")]
		public int Order_Checked([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Order_Unchecked")]
		public int Order_Unchecked([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Order_Insert")]
		public int Order_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="Int")] System.Nullable<int> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Int")] System.Nullable<int> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FullName", DbType="NVarChar(300)")] string fullName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(30)")] string mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(4000)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(4000)")] string description)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId, amount, fullName, email, mobile, address, description);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[File]")]
	public partial class File
	{
		
		private System.Guid _Id;
		
		private string _عنوان;
		
		private string _نوع;
		
		private int _حجم;
		
		private System.Data.Linq.Binary _Content;
		
		public File()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_عنوان", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string عنوان
		{
			get
			{
				return this._عنوان;
			}
			set
			{
				if ((this._عنوان != value))
				{
					this._عنوان = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_نوع", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string نوع
		{
			get
			{
				return this._نوع;
			}
			set
			{
				if ((this._نوع != value))
				{
					this._نوع = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_حجم", DbType="Int NOT NULL")]
		public int حجم
		{
			get
			{
				return this._حجم;
			}
			set
			{
				if ((this._حجم != value))
				{
					this._حجم = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this._Content = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Group]")]
	public partial class Group
	{
		
		private int _Id;
		
		private string _عنوان;
		
		public Group()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_عنوان", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string عنوان
		{
			get
			{
				return this._عنوان;
			}
			set
			{
				if ((this._عنوان != value))
				{
					this._عنوان = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Post")]
	public partial class Post
	{
		
		private int _Id;
		
		private string _عنوان;
		
		private string _چکیده;
		
		private string _متن;
		
		private System.DateTime _تاریخ;
		
		private string _Admin_Username;
		
		private string _زیر_گروه;
		
		private System.Nullable<int> _SubGroup_Id;
		
		private string _گروه;
		
		private int _GroupId;
		
		public Post()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_عنوان", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string عنوان
		{
			get
			{
				return this._عنوان;
			}
			set
			{
				if ((this._عنوان != value))
				{
					this._عنوان = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_چکیده", DbType="NVarChar(3000)")]
		public string چکیده
		{
			get
			{
				return this._چکیده;
			}
			set
			{
				if ((this._چکیده != value))
				{
					this._چکیده = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_متن", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string متن
		{
			get
			{
				return this._متن;
			}
			set
			{
				if ((this._متن != value))
				{
					this._متن = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_تاریخ", DbType="DateTime NOT NULL")]
		public System.DateTime تاریخ
		{
			get
			{
				return this._تاریخ;
			}
			set
			{
				if ((this._تاریخ != value))
				{
					this._تاریخ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Username", DbType="NVarChar(50)")]
		public string Admin_Username
		{
			get
			{
				return this._Admin_Username;
			}
			set
			{
				if ((this._Admin_Username != value))
				{
					this._Admin_Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[زیر گروه]", Storage="_زیر_گروه", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string زیر_گروه
		{
			get
			{
				return this._زیر_گروه;
			}
			set
			{
				if ((this._زیر_گروه != value))
				{
					this._زیر_گروه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubGroup_Id", DbType="Int")]
		public System.Nullable<int> SubGroup_Id
		{
			get
			{
				return this._SubGroup_Id;
			}
			set
			{
				if ((this._SubGroup_Id != value))
				{
					this._SubGroup_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_گروه", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string گروه
		{
			get
			{
				return this._گروه;
			}
			set
			{
				if ((this._گروه != value))
				{
					this._گروه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int NOT NULL")]
		public int GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this._GroupId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SubGroup")]
	public partial class SubGroup
	{
		
		private int _Id;
		
		private string _زیر_گروه;
		
		private int _GroupId;
		
		private string _گروه;
		
		public SubGroup()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[زیر گروه]", Storage="_زیر_گروه", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string زیر_گروه
		{
			get
			{
				return this._زیر_گروه;
			}
			set
			{
				if ((this._زیر_گروه != value))
				{
					this._زیر_گروه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int NOT NULL")]
		public int GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this._GroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_گروه", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string گروه
		{
			get
			{
				return this._گروه;
			}
			set
			{
				if ((this._گروه != value))
				{
					this._گروه = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Image")]
	public partial class Image
	{
		
		private System.Guid _Id;
		
		private string _عکس;
		
		private string _توضیحات;
		
		private System.Guid _File_Id;
		
		private int _حجم;
		
		private System.Data.Linq.Binary _Content;
		
		private System.Nullable<int> _Product_Id;
		
		private string _محصول;
		
		private System.Nullable<int> _Post_Id;
		
		private string _پست;
		
		public Image()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_عکس", DbType="NVarChar(600) NOT NULL", CanBeNull=false)]
		public string عکس
		{
			get
			{
				return this._عکس;
			}
			set
			{
				if ((this._عکس != value))
				{
					this._عکس = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_توضیحات", DbType="NVarChar(3000) NOT NULL", CanBeNull=false)]
		public string توضیحات
		{
			get
			{
				return this._توضیحات;
			}
			set
			{
				if ((this._توضیحات != value))
				{
					this._توضیحات = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_File_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid File_Id
		{
			get
			{
				return this._File_Id;
			}
			set
			{
				if ((this._File_Id != value))
				{
					this._File_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_حجم", DbType="Int NOT NULL")]
		public int حجم
		{
			get
			{
				return this._حجم;
			}
			set
			{
				if ((this._حجم != value))
				{
					this._حجم = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this._Content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Id", DbType="Int")]
		public System.Nullable<int> Product_Id
		{
			get
			{
				return this._Product_Id;
			}
			set
			{
				if ((this._Product_Id != value))
				{
					this._Product_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_محصول", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string محصول
		{
			get
			{
				return this._محصول;
			}
			set
			{
				if ((this._محصول != value))
				{
					this._محصول = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_Id", DbType="Int")]
		public System.Nullable<int> Post_Id
		{
			get
			{
				return this._Post_Id;
			}
			set
			{
				if ((this._Post_Id != value))
				{
					this._Post_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_پست", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string پست
		{
			get
			{
				return this._پست;
			}
			set
			{
				if ((this._پست != value))
				{
					this._پست = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product
	{
		
		private int _Id;
		
		private string _محصول;
		
		private string _توضیحات;
		
		private string _چکیده;
		
		private System.Guid _Image_Id;
		
		private string _زیر_گروه;
		
		private int _SubGroup_Id;
		
		private string _گروه;
		
		public Product()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_محصول", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string محصول
		{
			get
			{
				return this._محصول;
			}
			set
			{
				if ((this._محصول != value))
				{
					this._محصول = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_توضیحات", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string توضیحات
		{
			get
			{
				return this._توضیحات;
			}
			set
			{
				if ((this._توضیحات != value))
				{
					this._توضیحات = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_چکیده", DbType="NVarChar(3000) NOT NULL", CanBeNull=false)]
		public string چکیده
		{
			get
			{
				return this._چکیده;
			}
			set
			{
				if ((this._چکیده != value))
				{
					this._چکیده = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Image_Id
		{
			get
			{
				return this._Image_Id;
			}
			set
			{
				if ((this._Image_Id != value))
				{
					this._Image_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[زیر گروه]", Storage="_زیر_گروه", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string زیر_گروه
		{
			get
			{
				return this._زیر_گروه;
			}
			set
			{
				if ((this._زیر_گروه != value))
				{
					this._زیر_گروه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubGroup_Id", DbType="Int NOT NULL")]
		public int SubGroup_Id
		{
			get
			{
				return this._SubGroup_Id;
			}
			set
			{
				if ((this._SubGroup_Id != value))
				{
					this._SubGroup_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_گروه", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string گروه
		{
			get
			{
				return this._گروه;
			}
			set
			{
				if ((this._گروه != value))
				{
					this._گروه = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Orders")]
	public partial class Order
	{
		
		private int _Id;
		
		private int _Product_Id;
		
		private int _مقدار;
		
		private string _پست_الکترونیک;
		
		private string _موبایل;
		
		private string _آدرس;
		
		private string _توضیحات;
		
		private bool _مشاهده_شده;
		
		private string _نام_و_نام_خانوادگی;
		
		private string _محصول;
		
		private string _زیر_گروه;
		
		public Order()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Id", DbType="Int NOT NULL")]
		public int Product_Id
		{
			get
			{
				return this._Product_Id;
			}
			set
			{
				if ((this._Product_Id != value))
				{
					this._Product_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_مقدار", DbType="Int NOT NULL")]
		public int مقدار
		{
			get
			{
				return this._مقدار;
			}
			set
			{
				if ((this._مقدار != value))
				{
					this._مقدار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[پست الکترونیک]", Storage="_پست_الکترونیک", DbType="NVarChar(150)")]
		public string پست_الکترونیک
		{
			get
			{
				return this._پست_الکترونیک;
			}
			set
			{
				if ((this._پست_الکترونیک != value))
				{
					this._پست_الکترونیک = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_موبایل", DbType="NVarChar(30)")]
		public string موبایل
		{
			get
			{
				return this._موبایل;
			}
			set
			{
				if ((this._موبایل != value))
				{
					this._موبایل = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_آدرس", DbType="NVarChar(4000)")]
		public string آدرس
		{
			get
			{
				return this._آدرس;
			}
			set
			{
				if ((this._آدرس != value))
				{
					this._آدرس = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_توضیحات", DbType="NVarChar(4000)")]
		public string توضیحات
		{
			get
			{
				return this._توضیحات;
			}
			set
			{
				if ((this._توضیحات != value))
				{
					this._توضیحات = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[مشاهده شده]", Storage="_مشاهده_شده", DbType="Bit NOT NULL")]
		public bool مشاهده_شده
		{
			get
			{
				return this._مشاهده_شده;
			}
			set
			{
				if ((this._مشاهده_شده != value))
				{
					this._مشاهده_شده = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام و نام خانوادگی]", Storage="_نام_و_نام_خانوادگی", DbType="NVarChar(300)")]
		public string نام_و_نام_خانوادگی
		{
			get
			{
				return this._نام_و_نام_خانوادگی;
			}
			set
			{
				if ((this._نام_و_نام_خانوادگی != value))
				{
					this._نام_و_نام_خانوادگی = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_محصول", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string محصول
		{
			get
			{
				return this._محصول;
			}
			set
			{
				if ((this._محصول != value))
				{
					this._محصول = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[زیر گروه]", Storage="_زیر_گروه", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string زیر_گروه
		{
			get
			{
				return this._زیر_گروه;
			}
			set
			{
				if ((this._زیر_گروه != value))
				{
					this._زیر_گروه = value;
				}
			}
		}
	}
	
	public partial class Admin_LoginResult
	{
		
		private string _Username;
		
		public Admin_LoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
